# Mini Curso de Python


**Vetores e Matrizes**


Para um uso científico, o vetor numpy é mais recomendado, pois:

-  O NumPy é baseado em C, portanto tem um desempenho superior se comparado às operações com vetores originais do Python
- Os vetores se tornam matemáticos

In [2]:
#Declarando um vetor

import numpy as np

vet = np.array([9,7,4,1])
vet

array([9, 7, 4, 1])

In [2]:
#Mostrando o valor na posição 1 do vetor
vet[1]

7

In [3]:
#Atribuição automática - (valor inicial, valor final+1, passo omitido)  - passo = 1
vet = np.arange(1,10)
vet

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#Neste caso o passo está determinado em 2
vet = np.arange(0,10,2)
vet

array([0, 2, 4, 6, 8])

In [5]:
#Acessando posições específicas
vet = np.arange(10,20)
vet[[0,2,6]]

array([10, 12, 16])

In [6]:
#Acessando intervalo de posições (Atenção: o valor final é sempre somado de 1. Ou seja, no exemplo 
#ele irá de 2 a 4)
vet[2:5]

array([12, 13, 14])

In [7]:
#Acessando intervalo de posições com passo.
#Neste caso ele irá de 2 a 9 (10-1) com passo 3. Logo, ele irá pegar os indices 2, 5 e 8
#0    1   2   3   4   5  6   7    8   9
#10, 11, 12, 13, 14, 15, 16, 17, 18, 19

vet[2:10:3]

array([12, 15, 18])

In [8]:
#Concatenando dois arrays
vet1 = np.array([1,2,3,4,5,6])
vet2 = np.array([7,8,9])
vet = np.concatenate((vet1, vet2))
vet

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#Alterando valores de um array
vet[0]=10
vet

array([10,  2,  3,  4,  5,  6,  7,  8,  9])

In [7]:
#Multiplicação de elementos de vetores
vetA = np.array([2,3])
vetB = np.array([4,5])
vetA*vetB

array([ 8, 15])

In [9]:
#Para a realização de multiplicação de matrizes, usa-se o operador dot

vetA = np.array([2,3])
vetB = np.array([4,5])
np.dot(vetA,vetB)

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [11]:
#Para a realização de soma dos elementos de um vetor, usa-se o operador sum
vetA = np.array([2,3,8,9,10,7])
np.sum(vetA)

39

In [20]:
#Matrizes
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
#Posição na matriz A->A(i,j), i = linha, j=coluna
#Lembrado que em python as linhas e colunas começam em 0(zero)
print(A)
print(A[1,2])
print(A[2,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
7


In [24]:
#Acessando intervalos específicos linha e coluna
A[0:3,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [25]:
#Limite especificado para linha e todas as colunas disponíveis (:) em A
B=A[1:3,:]
B

array([[4, 5, 6],
       [7, 8, 9]])

In [26]:
#Para apagar uma linha ou coluna, basta chamar o comando delete
#passando como argumento a matriz, qual linha/coluna e se é linha (axis=0) ou coluna (axis=1)
np.delete(B, (1), axis=1)
B

array([[4, 5, 6],
       [7, 8, 9]])

In [27]:
#Para consultar as dimensões da matriz basta usar o comando shape

A.shape

(3, 3)

In [28]:
#Para consultar o tamanho total da matriz basta usar o comando size

A.size

9

In [30]:
#É possível criar uma matriz vazia baseado nas características de outra matriz
#Mesma dimensão e mesmos tipos de dados mas com valores aleatórios

np.empty_like(A)

array([[7236833184642769452, 7881144752318672485, 7310875413622977637],
       [7308895138223563308, 4120853257723722274, 3472613078282416952],
       [3474858302568215597, 3990532524511946036, 2477368164005197109]])

In [19]:
#Transposta (ou inversa) de uma matriz A => A’ ou transpose (A) logo, linha vira coluna e vice-versa.

A.transpose()

NameError: name 'A' is not defined

In [14]:
#Nas matrizes, o operador dot (multiplicação de matrizes) funciona

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [15]:
#Da mesma forma, o operador sum também realiza as operações de soma dos elementos de uma matriz
x = np.array([[1,2],[3,4]])

np.sum(x)

10

In [15]:
#Mas, numa matriz, pode-se escolher somar as linhas ou as colunas

x = np.array([[1,2],[3,4]])
print(x)
print("Soma das colunas", np.sum(x,axis=0))
print("Soma das linhas", np.sum(x,axis=1))

[[1 2]
 [3 4]]
Soma das colunas [4 6]
Soma das linhas [3 7]



***
## Exercício de Validação:

\begin{equation}
A = 
  \begin{bmatrix}
    1 & 2 & 3\\
    4 & 5 & 6 \\
    7 & 8 & 9
  \end{bmatrix}
\end{equation}

\begin{equation}
x = 
  \begin{bmatrix}
    -1\\
    0 \\
    2
  \end{bmatrix}
\end{equation}

Calcule:  
1) a matriz B, é a transposta de A  
2) C é a soma de A+B  
3) o Vetor y=x-1  
4) x'*y  
5) x*y'  
6) y*x'  


In [31]:
#Parte 1 - Montando as matrizes
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([[-1],[0],[2]])

print(A)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1]
 [ 0]
 [ 2]]


In [2]:
#Parte 2 - Resolvendo as questões
#1) a matriz B é a transposta de A

B = A.transpose()
print(B)}

NameError: name 'A' is not defined

In [34]:
#2) C é a soma de A+B

C = A+B
print(C)

[[ 2  6 10]
 [ 6 10 14]
 [10 14 18]]


In [35]:
#3) y=x-1

y = x-1
print(y)

[[-2]
 [-1]
 [ 1]]


In [1]:
#4) x’*y

x.transpose()*y

NameError: name 'x' is not defined

In [37]:
#5) x*y’

x*y.transpose()

array([[ 2,  1, -1],
       [ 0,  0,  0],
       [-4, -2,  2]])

In [2]:
#6) y*x’

y*x.transpose()

NameError: name 'y' is not defined

In [5]:
v = np.array([9,10])
w = np.array([11, 12])

print(v.dot(w))
print(np.dot(v, w))

219
219
